name: Feature Request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this feature solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
